Repository Haidra-Org/hordelib, pull requests merged in 2023-05, with the labels that each got.

#206 release: performance and fixes
  README.md
  examples/run_all_stress_tests.py
  examples/run_kudos_test.py
  examples/run_memory_test.py
  hordelib/initialisation.py
  hordelib/install_comfy.patch
  hordelib/model_database/esrgan.json
  hordelib/model_database/stable_diffusion.json
  hordelib/model_manager/base.py
  hordelib/model_manager/compvis.py
  hordelib/model_manager/hyper.py
  hordelib/nodes/node_model_loader.py
  tests/test_shared_model_manager.py
Labels: release:minor

#208 release: memory efficiency
  hordelib/pipeline_designs/pipeline_controlnet.json
  hordelib/pipeline_designs/pipeline_controlnet_hires_fix.json
  hordelib/pipeline_designs/pipeline_stable_diffusion.json
  hordelib/pipeline_designs/pipeline_stable_diffusion_hires_fix.json
  hordelib/pipeline_designs/pipeline_stable_diffusion_paint.json
  hordelib/pipelines/pipeline_controlnet.json
  hordelib/pipelines/pipeline_controlnet_hires_fix.json
  hordelib/pipelines/pipeline_stable_diffusion.json
  hordelib/pipelines/pipeline_stable_diffusion_hires_fix.json
  hordelib/pipelines/pipeline_stable_diffusion_paint.json
  hordelib/utils/logger.py
Labels: release:minor

#209 docs: update readme
  README.md
Labels: release:patch

#210 release: ci fixes
  .github/workflows/release.yml
Labels: release:patch

#211 release: fixes
  hordelib/model_database/stable_diffusion.json
  tox.ini
Labels: release:patch

#212 release: model fix
  .github/workflows/maintests.yml
  .github/workflows/prtests.yml
  hordelib/model_database/stable_diffusion.json
Labels: release:patch

#218 fix: remove ether real from exclude list
  hordelib/consts.py
Labels: release:patch

#227 Release: optimisations
  .gitignore
  examples/run_kudos_test.py
  hordelib/install_comfy.patch
  hordelib/model_manager/base.py
  hordelib/nodes/comfy_controlnet_preprocessors/uniformer/mmcv/cnn/bricks/registry.py
  hordelib/nodes/comfy_controlnet_preprocessors/uniformer/mmcv/cnn/builder.py
  hordelib/nodes/comfy_controlnet_preprocessors/uniformer/mmcv/cnn/utils/weight_init.py
  hordelib/nodes/comfy_controlnet_preprocessors/uniformer/mmcv/parallel/registry.py
  hordelib/nodes/comfy_controlnet_preprocessors/uniformer/mmcv/runner/builder.py
  hordelib/nodes/comfy_controlnet_preprocessors/uniformer/mmcv/runner/hooks/hook.py
  hordelib/nodes/comfy_controlnet_preprocessors/uniformer/mmcv/runner/optimizer/builder.py
  hordelib/nodes/comfy_controlnet_preprocessors/uniformer/mmcv/utils/registry.py
  hordelib/nodes/comfy_controlnet_preprocessors/uniformer/mmseg/core/seg/builder.py
  hordelib/nodes/comfy_controlnet_preprocessors/uniformer/mmseg/datasets/builder.py
  hordelib/nodes/comfy_controlnet_preprocessors/uniformer/mmseg/models/builder.py
  tox.ini
Labels: release:patch

#230 fix: handle image / mask size mismatch (#229)
  .gitignore
  hordelib/horde.py
Labels: release:patch

#237 release: fixes
  .gitignore
  examples/kudos.py
  examples/run_cache_test.py
  examples/run_kudos_test.py
  examples/run_memory_test.py
  hordelib/model_database/codeformer.json
  hordelib/model_database/safety_checker.json
  hordelib/model_database/stable_diffusion.json
  hordelib/model_manager/compvis.py
  hordelib/train.py
  images/test_db0-1024x1024.jpg
  kudos_models/inference-time-data-v20.json
  kudos_models/inference-time-data-validation-v20.json
  nn_inspect.ipynb
  requirements.txt
  run.cmd
  tests/test_horde_samplers.py
Labels: release:patch

#238 fix: pin timm library to v0.6.12
  .gitignore
  examples/run_cache_test.py
  examples/run_kudos_test.py
  examples/run_memory_test.py
  hordelib/model_database/codeformer.json
  hordelib/model_database/safety_checker.json
  hordelib/model_database/stable_diffusion.json
  images/test_db0-1024x1024.jpg
  kudos_models/inference-time-data-v20.json
  kudos_models/inference-time-data-validation-v20.json
  nn_inspect.ipynb
  run.cmd
Labels: release:patch

#243 fix: better memory management
  examples/run_memory_test.py
  hordelib/comfy_horde.py
  hordelib/install_comfy.patch
  hordelib/model_manager/base.py
  hordelib/model_manager/compvis.py
Labels: release:patch

#245 doc: update readme
  README.md
  hordelib/train.py
Labels: release:patch

#246 release v1.0.0
  README.md
Labels: release:major

#283 fix: treat inpainting models as standard models, removes diffusers 'support'
  examples/run_facefix.py
  examples/run_img2img_inpaint_mask.py
  examples/run_inpainting.py
  examples/run_long_prompt_check.py
  examples/run_upscale.py
  hordelib/consts.py
  hordelib/model_manager/base.py
  hordelib/model_manager/diffusers.py
  hordelib/model_manager/hyper.py
  hordelib/shared_model_manager.py
  tests/model_managers/test_diffusers.py
  tests/model_managers/test_hyper.py
  tests/test_horde_inference_painting.py
  tests/test_shared_model_manager.py
Labels: release:patch

#285 release: upgrades and fixes
  examples/lora_downloader.py
  examples/run_lora.py
  hordelib/comfy_horde.py
  hordelib/horde.py
  hordelib/install_comfy.patch
  hordelib/nodes/node_controlnet_model_loader.py
  tests/test_horde_inference.py
  tests/test_horde_lora.py
Labels: release:minor

#286 fix: minimum version for horde_model_reference
  requirements.txt
Labels: release:patch

#287 fix: horde_model_reference min version bump
  requirements.txt
Labels: release:patch

#299 release: fixes
  hordelib/comfy_horde.py
  hordelib/horde.py
  hordelib/model_manager/hyper.py
  hordelib/nodes/node_lora_loader.py
  hordelib/settings.py
  tests/test_horde_lora.py
Labels: release:patch

#306 release: lora model manager
  .gitignore
  README.md
  examples/run_lora.py
  hordelib/consts.py
  hordelib/horde.py
  hordelib/model_manager/hyper.py
  hordelib/model_manager/lora.py
  hordelib/nodes/node_lora_loader.py
  hordelib/shared_model_manager.py
  hordelib/utils/sanitizer.py
  requirements.txt
  tests/model_managers/test_mm_annotators.py
  tests/model_managers/test_mm_comvis.py
  tests/model_managers/test_mm_hyper.py
  tests/model_managers/test_mm_lora.py
  tests/model_managers/test_mm_safety_checker.py
  tests/test_comfy_install.py
  tests/test_horde_lora.py
  tests/test_shared_model_manager.py
Labels: release:minor

#308 fix: more robust downloads; resume, retry, don't delete files so hast…
  hordelib/model_manager/base.py
Labels: release:patch

#312 release: fixes
  hordelib/horde.py
  hordelib/model_manager/lora.py
Labels: release:patch

#315 fix: make fakescribble controlnet work again (#314)
  hordelib/model_manager/controlnet.py
Labels: release:patch

#325 release: fixes
  examples/make_index.py
  examples/make_index_all_models.py
  hordelib/model_manager/base.py
  hordelib/preload.py
  hordelib/settings.py
Labels: release:patch

#327 release: fixes
  .github/workflows/release.yml
  hordelib/model_manager/lora.py
  tests/model_managers/test_mm_lora.py
Labels: release:patch

#330 Release: Lora MM improvements
  .github/workflows/maintests.yml
  .github/workflows/prtests.yml
  hordelib/blip/caption.py
  hordelib/cache/cache.py
  hordelib/clip/bulk.py
  hordelib/clip/coca.py
  hordelib/clip/image.py
  hordelib/clip/interrogate.py
  hordelib/clip/text.py
  hordelib/horde.py
  hordelib/model_manager/lora.py
  tests/model_managers/test_mm_lora.py
  tests/test_horde_lora.py
  tox.ini
Labels: release:patch

#333 fix: logging error with loading cnet (#332)
  hordelib/preload.py
Labels: release:patch

#335 Release: Improve Lora MM seek
  hordelib/model_manager/lora.py
  hordelib/utils/sanitizer.py
  tests/model_managers/test_mm_lora.py
Labels: release:patch

#337 release: Handle lora names as ints better.
  hordelib/model_manager/lora.py
  tests/model_managers/test_mm_lora.py
Labels: release:patch

#342 release: important fixes
  examples/run_stress_test_job_collection.py
  hordelib/comfy_horde.py
  hordelib/install_comfy.patch
Labels: release:patch

#344 Release: Allow top10G loras without triggers
  hordelib/model_manager/lora.py
  tests/model_managers/test_mm_lora.py
Labels: release:patch

#346 Release: adhoc LoRas
  hordelib/horde.py
  hordelib/model_manager/lora.py
  tests/model_managers/test_mm_lora.py
  tests/test_horde_lora.py
Labels: release:patch
